services:
  clickhouse:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: omop_clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_DB=omop
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=default

  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: omop_postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=omop
      - POSTGRES_USER=omop_user
      - POSTGRES_PASSWORD=omop_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U omop_user -d omop"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  clickhouse_data:
    driver: local
  postgres_data:
    driver: local
